StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5D4E7AA3F57DB794}" {
   Id "M1_Action_LoadoutSaveName"
   Target_en_us "Save loadout"
   Target_ru_ru "Сохранить снаряжение"
   Status DEVELOPMENT_DONE
   Modified 1565425082
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D4E7AA3CF33B943}" {
   Id "M1_Notification_Loadout_Save_Failed_Reason_Forbidden_Item"
   Target_en_us "Loadout save failed. The item is forbidden: %1"
   Target_ru_ru "Не удалось сохранить снаряжение. Запрещенный предмет: %1"
   Status DEVELOPMENT_DONE
   Modified 1565425143
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D4E7AA3CB87AB86}" {
   Id "M1_Notification_Loadout_Save_Failed_Reason_Items_Quantity"
   Target_en_us "Loadout save failed. Max %1 items allowed: %2"
   Target_ru_ru "Не удалось сохранить снаряжение. Разрешено не более %2 шт: %1"
   Status DEVELOPMENT_DONE
   Modified 1565425139
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D4E7AA3C7477F47}" {
   Id "M1_UI_Button_LoadoutDefault"
   Target_en_us "Default"
   Target_ru_ru "Стандарт"
   Status DEVELOPMENT_DONE
   Modified 1565425134
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D4E7AA3C4096B9D}" {
   Id "M1_UI_Button_LoadoutSaved"
   Target_en_us "Saved"
   Target_ru_ru "Сохраненное"
   Status DEVELOPMENT_DONE
   Modified 1565425004
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D4E7AA3C114CCCA}" {
   Id "M1_UI_Text_Loadout"
   Target_en_us "Loadout:"
   Target_ru_ru "Снаряжение:"
   Status DEVELOPMENT_DONE
   Modified 1565425052
   Author "winse"
   LastChanged "winse"
  }
 }
}