StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5D22F4D691AAA019}" {
   Id "M1_Action_LoadoutSaveName"
   Target_en_us "Save loadout"
   Target_ru_ru "Сохранить снаряжение"
   Status DEVELOPMENT_DONE
   Modified 1562575245
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D22F4D66EE1DBAA}" {
   Id "M1_UI_Button_LoadoutDefault"
   Target_en_us "Default"
   Target_ru_ru "Стандарт"
   Status DEVELOPMENT_DONE
   Modified 1562575237
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D22F4D660A9EA4F}" {
   Id "M1_UI_Button_LoadoutSaved"
   Target_en_us "Saved"
   Target_ru_ru "Сохраненное"
   Status DEVELOPMENT_DONE
   Modified 1562575242
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D22F4D6710BF8EC}" {
   Id "M1_UI_Text_Loadout"
   Target_en_us "Loadout:"
   Target_ru_ru "Снаряжение:"
   Status DEVELOPMENT_DONE
   Modified 1562575232
   Author "winse"
   LastChanged "winse"
  }
 }
}